export default fontFamily = {
    poppins_black: "Poppins-Black",
    poppins_blackItalic: "Poppins-BlackItalic",
    poppins_bold: "Poppins-Bold",
    poppins_boldItalic: "Poppins-BoldItalic",
    poppins_extraBold: "Poppins-ExtraBold",
    poppins_extraBoldItalic: "Poppins-ExtraBoldItalic",
    poppins_extraLight: "Poppins-ExtraLight",
    poppins_extraLightItalic: "Poppins-ExtraLightItalic",
    poppins_italic: "Poppins-Italic",
    poppins_light: "Poppins-Light",
    poppins_LightItalic: "Poppins-LightItalic",
    poppins_Medium: "Poppins-Medium",
    poppins_MediumItalic: "Poppins-MediumItalic",
    poppins_Regular: "Poppins-Regular",
    poppins_semiBold: "Poppins-SemiBold",
    Poppins_semiBoldItalic: "Poppins-SemiBoldItalic",
    Poppins_thin: "Poppins-Thin",
    Poppins_thinItalic: "Poppins-ThinItalic",
  };
  