import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  mainBody: {
    flex: 1,
  },
  container: {
    width: '100%',
    flexDirecion: 'row',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingBottom: 0,
    flex: 1,
  },
  bodyContainer: {
    width: '100%',
    flexDirecion: 'row',
    paddingBottom: 0,
    flex: 1,
  },
  searchContainer: {
    marginTop: 10,
    padding: 10,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  inputContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonContainer: {
    //width: '20%',
    //justifyContent: 'center',
    //alignItems: 'center',
    height: 40,
  },
  scanButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 10,
    height: 40,
    width: '100%',
  },
  scanButtonText: {
    fontSize: 15,
    color: colors.light,
    fontWeight: 'bold',
  },
  promotiomSliderContainer: {
    margin: 5,
    height: 140,
    backgroundColor: '#fff',
  },
  primaryTextContainer: {
    padding: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    width: '100%',
    paddingTop: 10,
    paddingBottom: 10,
  },
  primaryText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
  },
  categoryContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    width: '100%',
  },
  emptyView: {width: 30},
  productCardContainer: {
    paddingLeft: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    height: 240,
    marginLeft: 10,
    paddingTop: 0,
  },
  productCardContainerEmpty: {
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 240,
    marginLeft: 10,
    paddingTop: 0,
  },
  productCardContainerEmptyText: {
    fontSize: 15,
    fontStyle: 'italic',
    color: colors.muted,
    fontWeight: '600',
  },
  orderSupportMainContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 10,
    paddingTop: 10,
    backgroundColor: '#ededed',
  },
  orderSupportContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    width: '25%',
    padding: 10,
  },
  orderSupportButtonIconSec: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  orderSupportButtonIcon: {
    width: 50,
    height: 50,
  },
  orderSupportButtonText: {
    fontSize: 14,
    color: '#000',
    fontWeight: '600',
    textAlign: 'center',
  },
});

export default styles;
